### ISSUE TITLE
When to release?

### ISSUE THREAD

**Issue by Maguire1999** [thucz/PanoGRF#1]
Hello, PanoGRF is a great work! I am looking forward to your open source code and dataset.

**Comment by thucz** [comment]
Official code requires internal review within the company before it can be released.  I cannot give you publicly, but I can give you my code privately. Please tell me your email, and I will send you my code later. Note: I haven't organized my code  and data completely.

**Comment by Maguire1999** [comment]
Thanks! My email is 610716365@qq.com
