### ISSUE TITLE
Preprocess code for Replica and Residential datasets

### ISSUE THREAD

**Issue by iamblitzcrank** [thucz/PanoGRF#2]
Hello, I found the code for preprocessing MP3D dataset using habitat simulator.
Could you upload the preprocess code for Replica and Residential datasets?

Thank you!

**Comment by thucz** [comment]
Hi! I just uploaded the preprocessing code. See [dataset/replica_make/README.md](https://github.com/thucz/PanoGRF/blob/main/dataset/replica_make/README.md) and [dataset/residential_make/README.md](https://github.com/thucz/PanoGRF/blob/main/dataset/residential_make/README.md)
