### ISSUE TITLE
How to Test Only the Depth Estimation Module (MVS)?

### ISSUE THREAD

**Issue by LeonATP** [thucz/PanoGRF#5]
Hi,

Thank you for open-sourcing such an outstanding project!

I am currently working on multi-view depth estimation for panoramic images and would like to use your multi-view depth estimation module to evaluate on the Matterport3D dataset. However, I haven't found any specific guidance on how to proceed. It seems possible by modifying the relevant code and parameters in train_depth.py and train_mvs.sh, but I'm wondering if there is a simpler and more straightforward approach to achieve this.

Any guidance or assistance would be greatly appreciated!

Best regards,
Zhongmiao Yan

**Comment by thucz** [comment]
comment:
https://github.com/thucz/PanoGRF/blob/a8fb5c80e1c8653e926a6bc2770593d71b1f92af/configs/train/depth/m3d_mvs.yaml#L45-L48

uncomment:
https://github.com/thucz/PanoGRF/blob/a8fb5c80e1c8653e926a6bc2770593d71b1f92af/configs/train/depth/m3d_mvs.yaml#L50-L55

Then run:
https://github.com/thucz/PanoGRF/blob/a8fb5c80e1c8653e926a6bc2770593d71b1f92af/train_scripts/train_depth/train_mvs.sh#L1

**Comment by LeonATP** [comment]
Thank you for your prompt response! I have followed your instructions, but the visualized pred_depth image I obtained seems to exhibit periodic patterns and incorrect scaling. Could you tell me where the problem might be? 

I have attached the resulting images from my run: the first one is depth_gt.jpg, and the second one is depth_pred.jpg.

![11_depth_gt](https://github.com/user-attachments/assets/2d957737-4a6c-4a8c-b59a-0cae2b1e1148)
![11_depth_pred](https://github.com/user-attachments/assets/0d7667da-d85f-4cc1-b35a-71f59907022e)

Again, thank you for your assistance.

Best regards, Zhongmiao Yan

**Comment by thucz** [comment]
You might confuse the output channel order. I am not very sure. Maybe you need to check the output dimension with `import pdb; pdb.set_trace()`.

**Comment by LeonATP** [comment]
Thank you for your response. I have resolved the issue—it was due to confusing the dimensions of RGB images during data input. As a result, I have successfully obtained the depth prediction results I needed. I will go ahead and close this issue. 
Once again, thank you for open sourcing this outstanding work!
