### ISSUE TITLE
How to test the depth estimation module on a real dataset?

### ISSUE THREAD

**Issue by Leon-Williams9** [thucz/PanoGRF#6]
Great work! Thank you for open-sourcing this impressive research.

I noticed that in your paper, you mention testing depth estimation on the Matterport3D dataset with good results, but the data appears to be generated from a Habitat environment. I’m interested in testing multi-view stereo depth estimation on real-world datasets, specifically by testing directly on panoramic images from the [Matterport3D 360 dataset](https://researchdata.bath.ac.uk/1126/) or the [Stanford2D3D dataset](http://buildingparser.stanford.edu/dataset.html). These datasets provide color panoramic images, real depth values, and true camera poses, which meet the model's requirements .

I’ve written a script to load the datasets based on your code and attempted testing on the 18 test scenes of the [Matterport3D 360 dataset](https://researchdata.bath.ac.uk/1126/). However, the results didn’t meet my expectations. It seems that there is a discrepancy between the scale of the predicted values and the actual scale.I’ve attached the evaluation metrics groundtruth depth and pred depth visual results below for your reference.

![Screenshot from 2024-11-13 23-56-03](https://github.com/user-attachments/assets/9a220247-54ff-4318-a6a9-984b9c0d2faa)

![22_depth_gt](https://github.com/user-attachments/assets/ba81925e-4e92-4b5d-adcc-d7e9b4dfc847)

![22_depth_pred](https://github.com/user-attachments/assets/937207f0-157d-46b8-84fe-8aaa8337e404)

I suspect the issue might be due to the following reasons:

Pose reading errors: I thought there might be issues with how I read the pose data, but I have carefully checked the projection in the cost volume and the coordinate transformation code, and I believe my input pose data is correct.

Variable baseline in real datasets: I noticed that in real datasets, the camera baseline isn’t fixed, and I recall you mentioned the baseline issue in your paper during each test. I’m wondering if the model struggles to adapt to varying baselines.

I would greatly appreciate any guidance or suggestions you might have regarding this issue.

Thank you again for your excellent work!

**Comment by thucz** [comment]
Recently, I'm rushing a paper about 360 multi-viewpoint reconstruction with varying camera baselines for CVPR2025. Please send me email after that. At that time, I will try to give you a new pretrained model along with test code, which predict much better depth than PanoGRF.

**Comment by thucz** [comment]
My email is zhengchenecho@gmail.com

**Comment by Leon-Williams9** [comment]
Thank you for your quick response. If I continue to work on this line, I may contact you via email weeks later. I wish you smooth writing and successful submission.

**Comment by Leon-Williams9** [comment]
I’ve sent you an email requesting further assistance, as I’m very interested in your work. I was wondering if you would be willing to share more details about your new research, or perhaps provide access to any pre-trained models and testing code? I would greatly appreciate any form of help, and I look forward to hearing from you.

Best regards.

**Comment by thucz** [comment]
The code could be seen in https://github.com/thucz/splatter360 . But the dataset is too large (about 4T for HM3D and 90G for Replica). I'm trying to upload them these days.


The test code is currently mainly for novel view synthesis. But its depth prediction is supervised by ground truth depth and much sharper and accurate than PanoGRF and MVSplat. The code about predicted depth at the inference time is [here
](https://github.com/thucz/splatter360/blame/main/src/model/model_wrapper_erp.py#L327).

You also need to adjust our code to your dataset, especially for [spherical projection](https://github.com/thucz/splatter360/blob/main/src/geometry/utils360.py) and [dataloader](https://github.com/thucz/splatter360/blob/main/src/dataset/dataset_hm3d.py).
